### ISSUE TITLE
Welcome Astrid

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-compare#1]
Hi @astridx,

Thanks for volunteering to maintain this plugin https://github.com/maplibre/maplibre-gl-js-docs/discussions/51. Let me know if you need some help with the migration.

Best,
Oliver

**Comment by astridx** [comment]
Until now, I have always selected a repo as a fork and then created a PR. I can't add the [empty repo](https://stackoverflow.com/questions/39013301/how-do-i-fork-an-empty-repository-on-github) as a fork. Or at least I don't know how. 
Could you please put a file (LICENSE or README.md) in it, or explain to me how best to proceed?

**Comment by wipfli** [comment]
I pushed to main. Does it work now?

**Comment by astridx** [comment]
Thank you, yes. Now I could open the PR. I hope everything is fine:
https://github.com/maplibre/maplibre-gl-compare/pulls
