### ISSUE TITLE
Any advice on how to integrate this with react-map-gl?

### ISSUE THREAD

**Issue by akexinad** [maplibre/maplibre-gl-compare#3]

**Comment by astridx** [comment]
~~Have you read this:
https://visgl.github.io/react-map-gl/docs/get-started/get-started#using-with-a-mapbox-gl-fork~~

Sorry, I read to fast.

I tried it here: https://blog.astrid-guenther.de/maplibregl-swipe

Does that help you? Otherwise, feel free to ask.

We are currently working on the publication on NPM.

**Comment by akexinad** [comment]
Sorry @astridx but are you sure that link is correct?

I can't see any use of `react-map-gl` in that link you sent me.

Thanks for the prompt reply.

**Comment by astridx** [comment]
Sorry for the confusion. You are right. I was just looking on my smartphone and answered too quickly. Mapbox is still integrated in the linked Gatsby Starter. That didn't work without a hack at the time I worked on it.  (https://github.com/maplibre/maplibre-gl-compare/blob/61f0bfd4a1268984b342fbeef2af834ce8ff165a/index.js#L225)

The npm version is being worked on and it will soon be possible in a separate package without the hack.

**Comment by akexinad** [comment]
No worries at all thank you for the clarification.

If there is any way I can help please don't hesitate to reach out.

**Comment by astridx** [comment]
@akexinad 
maplibre-gl-compare is now an npm package and you can import it: https://www.npmjs.com/package/@maplibre/maplibre-gl-compare
 Do you need more help?

**Comment by akexinad** [comment]
Hey @astridx,

Yep I got it to work with `CRA`!

However with `Next.js` it works on the first compilation, but when I restart the server I get a `window is undefined` error:

![image](https://user-images.githubusercontent.com/44803303/129427453-ccd1e2f0-8451-468b-b87d-4f1c6421b591.png)


This is my working code with CRA:

```
//@ts-ignore
import * as MapLibreCompare from "@maplibre/maplibre-gl-compare";
import React, {
    CSSProperties,
    useCallback,
    useEffect,
    useRef,
    useState,
} from "react";
import ReactMapGL, { MapRef } from "react-map-gl";
import "./mapLibreCompare.css";

export const MapCompare = () => {
   
    const key = "MAPTILE_KEY";

    const [viewport, setViewport] = useState({
        latitude: 37.7577,
        longitude: -122.4376,
        zoom: 8,
    });

    const handleViewportChange = useCallback(
        (newViewport) => setViewport(newViewport),
        []
    );

    let beforeRef = useRef<MapRef>();
    let afterRef = useRef<MapRef>();

    const style: CSSProperties = {
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
    };

    useEffect(() => {
        const comparison = new MapLibreCompare(
            beforeRef,
            afterRef,
            "#comparison-container"
        );

        return () => {
            comparison.remove();
        };
    }, []);

    return (
        <div id="comparison-container" style={{ ...style, width: "100%" }}>
            <ReactMapGL
                ref={(ref) => (beforeRef = ref?.getMap())}
                width="100%"
                height="100%"
                style={style}
                {...viewport}
                onViewportChange={handleViewportChange}
                mapStyle={`https://api.maptiler.com/maps/streets/style.json?key=${KEY}`}
            />
            <ReactMapGL
                ref={(ref) => (afterRef = ref?.getMap())}
                width="100%"
                height="100%"
                style={style}
                {...viewport}
                onViewportChange={handleViewportChange}
                mapStyle={`https://api.maptiler.com/maps/hybrid/style.json?key=${KEY}`}
            />
        </div>
    );
};
```

**Comment by astridx** [comment]
I have no experience with `nextjs.org`. In [Gatsbyjs ](https://github.com/gatsbyjs/gatsby) I can import `maplibre-gl-compare` without any problems. Here I also use the [create-react-app](https://github.com/facebook/create-react-app). So I think it is a `nextjs.org` special thing. Google shows me [this ](https://stackoverflow.com/questions/60738486/nextjs-react-webpackerror-window-is-not-defined) link, which reads to me like it solves your problem. It links this documentation page: https://nextjs.org/docs/advanced-features/dynamic-import. 

Is that true?

**Comment by akexinad** [comment]
Yep problem solved. Cheers!
